@startuml
left to right direction

skinparam packageStyle rectangle
skinparam usecase {
    BackgroundColor white
    BorderColor black
}
skinparam actor {
    BackgroundColor white
    BorderColor black
}

actor "Pengunjung" as pengunjung

rectangle "Sub-Sistem Pengunjung Web" <<subsystem>> {
    usecase "Melihat Informasi Publik\n(Berita, UMKM, Peta Desa)" as UC_Info
}

' Relasi
pengunjung -- UC_Info

@enduml
